# Generated by Django 4.2.4 on 2023-08-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('D', 'Dress'), ('O', 'Outerwear'), ('U', 'Undergarments'), ('A', 'Accessories'), ('F', 'Footwear'), ('AW', 'Activewear'), ('SW', 'Swimwear'), ('SL', 'Sleepwear'), ('FW', 'Formal wear'), ('I', 'Intimates'), ('C', 'Costume')], default='C', max_length=2)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('garments', models.ManyToManyField(to='DressYourSelf.garment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressYourSelf.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='garment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressYourSelf.user'),
        ),
    ]
