# Generated by Django 4.2.4 on 2023-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressYourSelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
