# Generated by Django 4.2.4 on 2023-08-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressYourSelf', '0002_alter_garment_user_alter_outfit_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(null=True, upload_to='outfits/'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='image',
            field=models.ImageField(upload_to='garments/'),
        ),
    ]
