# Generated by Django 4.2.4 on 2023-10-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressYourSelf', '0002_alter_garment_name_alter_outfit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='garment',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='outfit',
            unique_together={('name', 'user')},
        ),
    ]
