# Generated by Django 4.2.4 on 2023-08-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressYourSelf', '0003_outfit_image_alter_garment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
    ]
