# Generated by Django 4.2.4 on 2023-08-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressYourSelf', '0004_alter_garment_brand_alter_garment_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(null=True, upload_to='outfits/'),
        ),
    ]
